name: Version
on:
push:
branches:
- release/next
jobs:
version:
name: Version
runs-on: ubuntu-latest
strategy:
matrix:
node-version: [16]
steps:
- name: Checkout Branch
uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # actions/checkout@v3 | releases,v3.6.0
- name: Install pnpm
uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # pnpm/action-setup@v4
- name: Use Node.js ${{ matrix.node-version }}
uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # actions/setup-node@v3 | releases,v3.9.1
with:
node-version: ${{ matrix.node-version }}
cache: 'pnpm'
- name: Install Dependencies
run: pnpm install
- name: Setup git user
run: pnpm run setup-git
- name: Create Release Pull Request
uses: changesets/action@e0145edc7d9d8679003495b11f87bd8ef63c0cba # changesets/action@v1
with:
version: pnpm run version
commit: 'chore: update versions'
title: 'chore: update versions'
setupGitUser: false
env:
GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_TOKEN }}