name: "PR guard"
on:
pull_request:
types: [opened, synchronize, reopened]
jobs:
check-dist:
if: github.event.pull_request.head.repo.full_name != github.repository
runs-on: ubuntu-latest
permissions:
pull-requests: write
steps:
- uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # dorny/paths-filter@v3 | master,v3.0.2
id: filter
with:
filters: |
dist:
- 'dist/**'
- name: Comment if dist/ was changed
if: steps.filter.outputs.dist == 'true'
uses: peter-evans/create-or-update-comment@71345be0265236311c031f5c7866368bd1eff043 # peter-evans/create-or-update-comment@v4 | v4.0.0
with:
token: ${{ secrets.GITHUB_TOKEN }}
issue-number: ${{ github.event.pull_request.number }}
body: |
⚠️ **Warning!** You have made changes to the `dist/` directory.
These files should not be edited manually as they will be built by our CI/CD pipeline during release.
Please remove these changes from the pull request.