name: Mark stale issues and pull requests
on:
schedule:
- cron: '44 0 * * *'
jobs:
stale:
runs-on: ubuntu-latest
permissions:
issues: write
pull-requests: write
steps:
- uses: actions/stale@f7176fd3007623b69d27091f9b9d4ab7995f0a06 # actions/stale@v5 | releases,v5.2.1
with:
repo-token: ${{ secrets.GITHUB_TOKEN }}
stale-issue-message: 'This issue has been inactive for a while, marking as stale.'
stale-pr-message: 'This pull request has been inactive for a while, marking as stale.'
stale-issue-label: 'stale'
stale-pr-label: 'stale'
days-before-stale: 14
days-before-close: 7
exempt-assignees: 'Chalarangelo'
close-issue-message: 'This issue has been stale for a while, closing due to inactivity.'
close-pr-message: 'This pull request has been inactive for a while, closing due to inactivity.'