name: Run tests
permissions:
contents: read
on:
push:
branches: [ master ]
pull_request:
branches: [ master ]
jobs:
js_tests:
name: 'Node.js ${{ matrix.node-version }} tests'
runs-on: ubuntu-latest
strategy:
matrix:
node-version: [22.14.0]
steps:
- uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
- name: Use Node.js ${{ matrix.node-version }}
uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # actions/setup-node@v1 | servicing,v1.4.6
with:
node-version: ${{ matrix.node-version }}
- run: npm ci
- run: npm test