name: Semantic PR title
on:
pull_request:
types:
- opened
- edited
- synchronize
jobs:
semantic:
runs-on: ubuntu-latest
steps:
- uses: amannn/action-semantic-pull-request@0723387faaf9b38adef4775cd42cfd5155ed6017 # amannn/action-semantic-pull-request@v5 | v5.5.3
env:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}