name: 'Build & Test'
on:
push:
branches:
- main
pull_request:
branches:
- main
jobs:
build:
name: 'Build (${{ matrix.os }}, Node ${{ matrix.node }})'
runs-on: ${{ matrix.os }}
strategy:
fail-fast: false
matrix:
os:
- 'ubuntu-latest'
node:
- '16'
steps:
- uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # actions/checkout@v3 | releases,v3.6.0
- uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # actions/setup-node@v3 | releases,v3.9.1
with:
node-version: ${{ matrix.node }}
cache: 'npm'
- name: Install dependencies
run: npm ci --prefer-offline
- name: Build
run: npm run build
integration:
name: 'Integration Tests (${{ matrix.os }}, Node ${{ matrix.node }})'
runs-on: ${{ matrix.os }}
strategy:
fail-fast: false
matrix:
os:
- 'ubuntu-latest'
- 'macos-latest'
- 'windows-latest'
node:
- '16'
steps:
- uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # actions/checkout@v3 | releases,v3.6.0
- name: Setup node
uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # actions/setup-node@v3 | releases,v3.9.1
with:
node-version: ${{ matrix.node }}
cache: 'npm'
- name: Install dependencies
run: npm ci --prefer-offline
# The integration tests are run with yarn, so we need to install it.
- name: Install yarn
run: npm i -g yarn
- name: Run integration tests
run: npm run test:integration
e2e-simple:
name: E2E Simple
uses: ./.github/workflows/e2e-base.yml
with:
testScript: 'tasks/e2e-simple.sh'
e2e-installs:
name: E2E Installs
uses: ./.github/workflows/e2e-base.yml
with:
testScript: 'tasks/e2e-installs.sh'
e2e-kitchensink:
name: E2E Kitchensink
uses: ./.github/workflows/e2e-base.yml
with:
testScript: 'tasks/e2e-kitchensink.sh'