name: package
on: push
jobs:
docker-ubuntu:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
- name: Set up Docker Buildx
uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # docker/setup-buildx-action@v3 | master,v3.11.1
- name: Login to GitHub Container Registry
uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # docker/login-action@v3 | v3.4.0
with:
registry: ghcr.io
username: ${{ github.repository_owner }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build and push Docker image
uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # docker/build-push-action@v6 | master,v6.18.0
with:
context: .
build-args: "UBUNTU_VERSION=24.04"
file: watchman/build/package/ubuntu-env/Dockerfile
push: true
tags: ${{ format('ghcr.io/{0}/watchman-build-env:latest', github.repository) }}
clone-and-build-and-package-ubuntu:
needs: docker-ubuntu
runs-on: ubuntu-latest
container:
image: ${{ format('ghcr.io/{0}/watchman-build-env:latest', github.repository) }}
steps:
- name: Checkout code
uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
- name: rustup default stable
run: rustup default stable
- name: Install system dependencies
run: ./install-system-packages.sh
- name: Test cargo
run: cargo --help
- name: Fix dubious ownership
run: git config --global --add safe.directory /__w/watchman/watchman
- name: Build Watchman binaries
run: ./autogen.sh
- name: Make .deb
run: ./watchman/build/package/make-deb.sh