name: Secret Leaks
permissions:
contents: read
jobs:
trufflehog:
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
with:
fetch-depth: 0
- name: Secret Scanning
uses: trufflesecurity/trufflehog@cb1b3b72fb250b40d3121225e94b4acbb283947e # trufflesecurity/trufflehog@main
with:
extra_args: --results=verified,unknown