name: Links Checker
on:
## Allow triggering this workflow manually via GitHub CLI/web
workflow_dispatch:
## Run this workflow automatically every month
schedule:
- cron: '0 0 1 * *'
jobs:
link_checker:
name: Check links and create automated issue if needed
runs-on: ubuntu-latest
env:
REPORT_FILE: links-report
steps:
## Check out code using Git
- uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # actions/checkout@v3 | releases,v3.6.0
- name: Check all links at README.md but skips translations files
id: lychee
uses: lycheeverse/lychee-action@f1da3291e1d03cbe11a413ae9f16b62fec99e6b6 # lycheeverse/lychee-action@v1.4.1
with:
output: ${{ env.REPORT_FILE }}
format: markdown
## Do not fail this step on broken links
fail: false
## Allow pages replying with 200 (Ok), 204 (No Content),
## 206 (Partial Content) in at most 20 seconds with HTML content.
## max-concurrency was 20, getting network errors
args: >-
--verbose
--accept 200,204,206
--headers "accept=text/html"
--timeout 20
--max-concurrency 3
--no-progress
README.md
env:
## Avoid rate limiting when checking github.com links
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
- name: Lychee's exit code
## https://github.com/lycheeverse/lychee#exit-codes
run: echo Lychee exit with ${{ steps.lychee.outputs.exit_code }}
- name: Find the last report issue open
uses: micalevisk/last-issue-action@18b4e4f7c1daa4dae44daa55a6614e592d03b154 # micalevisk/last-issue-action@v1.2 | v1,v1.2.4
id: last_issue
with:
state: open
labels: |
report
automated issue
env:
GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
- name: Create issue from report file
if: ${{ steps.last_issue.outputs.has_found == 'false' }}
uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f # peter-evans/create-issue-from-file@v4 | v4.0.1
with:
title: Link checker report
content-filepath: ${{ env.REPORT_FILE }}
issue-number: ${{ steps.last_issue.outputs.issue_number }}
labels: |
report
automated issue
- name: Update last report open issue created
if: ${{ steps.last_issue.outputs.has_found == 'true' }}
uses: peter-evans/create-issue-from-file@433e51abf769039ee20ba1293a088ca19d573b7f # peter-evans/create-issue-from-file@v4 | v4.0.1
with:
title: Link checker report
content-filepath: ${{ env.REPORT_FILE }}
issue-number: ${{ steps.last_issue.outputs.issue_number }}
labels: |
report
automated issue
- name: Close last report open issue
if: ${{ steps.lychee.outputs.exit_code == 0 }}
uses: peter-evans/close-issue@1373cadf1f0c96c1420bc000cfba2273ea307fd1 # peter-evans/close-issue@v2 | v2.2.0
with:
issue-number: ${{ steps.last_issue.outputs.issue_number }}