name: Dart
on:
push:
branches: ["main"]
paths: ["codes/dart/**/*.dart"]
pull_request:
branches: ["main"]
paths: ["codes/dart/**/*.dart"]
workflow_dispatch:
permissions:
contents: read
jobs:
build:
name: Dart ${{ matrix.dart-sdk }} on ${{ matrix.os }}
runs-on: ${{ matrix.os }}
strategy:
matrix:
os: [ubuntu-latest, macos-latest, windows-latest]
dart-sdk: [stable]
steps:
- uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
- name: Set up Dart ${{ matrix.dart-sdk }}
uses: dart-lang/setup-dart@e51d8e571e22473a2ddebf0ef8a2123f0ab2c02c # dart-lang/setup-dart@v1 | v1.7.1
with:
sdk: ${{ matrix.dart-sdk}}
- name: Run format
run: dart format codes/dart
- name: Run analyze
run: dart analyze codes/dart
- name: Run build
run: dart codes/dart/build.dart