name: Swift
on:
push:
branches: ["main"]
paths: ["codes/swift/**/*.swift"]
pull_request:
branches: ["main"]
paths: ["codes/swift/**/*.swift"]
workflow_dispatch:
jobs:
build:
name: Swift on ${{ matrix.os }}
runs-on: ${{ matrix.os }}
strategy:
matrix:
os: ["ubuntu-22.04", "macos-14"]
steps:
- uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
- name: Build
run: swift build --package-path codes/swift