name: .NET
on:
push:
branches: [ "main" ]
paths: ["codes/csharp/**/*.cs"]
pull_request:
branches: [ "main" ]
paths: ["codes/csharp/**/*.cs"]
workflow_dispatch:
jobs:
build:
name: .NET ${{ matrix.dotnet-version }} on ${{ matrix.os }}
runs-on: ${{ matrix.os }}
defaults:
run:
working-directory: codes/csharp/
strategy:
matrix:
os: [ubuntu-latest, macos-latest, windows-latest]
dotnet-version: ["8.0.x"]
steps:
- uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
- name: Setup .NET ${{ matrix.dotnet-version }}
uses: actions/setup-dotnet@55ec9447dda3d1cf6bd587150f3262f30ee10815 # actions/setup-dotnet@v3 | releases,v3.4.2
with:
dotnet-version: ${{ matrix.dotnet-version }}
- name: Restore dependencies
run: dotnet restore hello-algo.csproj
- name: Build
run: dotnet build --no-restore hello-algo.csproj
- name: Test with dotnet
run: dotnet test hello-algo.csproj