name: Ruby
on:
push:
branches: [ "main" ]
paths: ["codes/ruby/**/*.rb"]
pull_request:
branches: [ "main" ]
paths: ["codes/ruby/**/*.rb"]
workflow_dispatch:
permissions:
contents: read
jobs:
test:
name: Ruby ${{ matrix.ruby-version }} on ${{ matrix.os }}
runs-on: ${{ matrix.os }}
strategy:
matrix:
os: [ubuntu-latest, macos-latest, windows-latest]
ruby-version: ['3.3']
steps:
- uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
- name: Set up Ruby
uses: ruby/setup-ruby@a9bfc2ecf3dd40734a9418f89a7e9d484c32b990 # ruby/setup-ruby@v1 | master,v1.248.0
with:
ruby-version: ${{ matrix.ruby-version }}
- name: Run tests
run: ruby codes/ruby/test_all.rb