name: Java
on:
push:
branches: [ "main" ]
paths: ["codes/java/**/*.java"]
pull_request:
branches: [ "main" ]
paths: ["codes/java/**/*.java"]
workflow_dispatch:
jobs:
build:
runs-on: ubuntu-20.04
strategy:
matrix:
java: [ '11', '17' ]
name: Java ${{ matrix.Java }} sample
steps:
- uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
- name: Setup java
uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 # actions/setup-java@v3 | releases,v3.14.1
with:
distribution: 'temurin'
java-version: ${{ matrix.java }}
- run: javac -d codes/java/build codes/java/**/*.java