name: "CodeQL"
on:
workflow_call:
inputs:
golang_version:
required: true
type: string
jobs:
analyze:
name: Analyze Go code with CodeQL
runs-on: ubuntu-latest
timeout-minutes: 360
permissions:
security-events: write
packages: read
steps:
- name: Checkout repository
uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
- name: Install Go
uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # actions/setup-go@v5 | v5.5.0
with:
go-version: ${{ inputs.golang_version }}
- name: Initialize CodeQL
uses: github/codeql-action/init@d6bbdef45e766d081b84a2def353b0055f728d3e # github/codeql-action/init@v3
with:
languages: go
build-mode: manual
- shell: bash
run: |
make build
- name: Perform CodeQL Analysis
uses: github/codeql-action/init@d6bbdef45e766d081b84a2def353b0055f728d3e # github/codeql-action/init@v3
with:
category: "/language:go"