name: Helm
on:
workflow_call:
inputs:
golang_version:
required: true
type: string
jobs:
test:
name: Test
runs-on: ubuntu-latest
steps:
- name: Checkout code
uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
- name: Install Go
uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # actions/setup-go@v5 | v5.5.0
with:
go-version: ${{ inputs.golang_version }}
- run: make test-helm