name: Weekly CDT Inspector
on:
schedule:
- cron: "30 2 * * 2,5" # Tuesday and Friday at 2:30
env:
JAVA_HOME: ${{ github.workspace }}/jdk
JDK_VERSION: "latest"
MX_PATH: ${{ github.workspace }}/mx
SE_SKIP_DRIVER_IN_PATH: "true"
jobs:
build:
runs-on: ubuntu-latest
if: github.repository == 'oracle/graal'
steps:
- name: Checkout oracle/graal
uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
with:
path: ${{ github.workspace }}/graal
- name: Checkout oracle/graaljs
uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
with:
repository: oracle/graaljs
sparse-checkout: |
graal-js
path: ${{ github.workspace }}/js
- name: Checkout graalvm/mx
uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
with:
repository: graalvm/mx.git
ref: master
path: ${{ env.MX_PATH }}
- name: Set up Python
uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # actions/setup-python@v5 | v5.6.0
with:
python-version: '3.8'
- name: Fetch LabsJDK
run: |
mkdir jdk-dl
${MX_PATH}/mx --java-home= fetch-jdk --jdk-id labsjdk-ce-${JDK_VERSION} --to jdk-dl --alias ${JAVA_HOME}
- run: |
cd ${{ github.workspace }}/graal/vm
${MX_PATH}/mx --dy /tools,graal-js build
cd tests/gh_workflows/CDTInspectorTest
mvn -q compile
mvn -q exec:exec -Dtestargs="${{ github.workspace }}/graal/sdk/latest_graalvm_home/bin/js scripts/StepTest.js"