name: Weekly Spring Tests
on:
pull_request:
paths:
- '.github/workflows/spring.yml'
schedule:
- cron: '0 4 * * 1'
workflow_dispatch:
env:
SPRING_PETCLINIC_PATH: ${{ github.workspace }}/spring-petclinic
SPRING_JAVA_VERSION: 21
permissions:
contents: read # to fetch code (actions/checkout)
jobs:
build-graalvm-and-spring:
name: Native Tests
runs-on: ubuntu-22.04
if: (github.event_name == 'schedule' && github.repository == 'oracle/graal') || (github.event_name != 'schedule')
steps:
- name: Checkout oracle/graal
uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
- name: Build GraalVM JDK
uses: ./.github/actions/build-graalvm
with:
java-version: ${{ env.SPRING_JAVA_VERSION }}
- name: Checkout spring-projects/spring-petclinic
uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
with:
repository: spring-projects/spring-petclinic
path: ${{ env.SPRING_PETCLINIC_PATH }}
- name: Run nativeTest in spring-petclinic
run: |
cd ${{ env.SPRING_PETCLINIC_PATH }}
./gradlew nativeTest