name: Weekly Native Image Layer Building Tests
on:
pull_request:
paths:
- '.github/workflows/ni-layers.yml'
- 'vm/tests/gh_workflows/NILayerTests/**'
schedule:
- cron: "0 0 * * 1" # Once a week, at midnight on Monday (00:00 UTC)
workflow_dispatch:
env:
LIBRARY_METADATA_PATH: ${{ github.workspace }}/vm/tests/gh_workflows/NILayerTests
JAVA_VERSION: 21
PYTHON_VERSION: 3.12.3
jobs:
build-graalvm-and-populate-matrix:
name: Build GraalVM and populate matrix
runs-on: ubuntu-latest
if: (github.repository=='oracle/graal')
outputs:
matrix: ${{ steps.set-matrix.outputs.matrix }}
steps:
- name: Checkout oracle/graal
uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
- name: Build GraalVM JDK
uses: ./.github/actions/build-graalvm
with:
native-images: 'native-image,native-image-configure,lib:native-image-agent'
components: 'Native Image,Native Image Configure Tool'
java-version: ${{ env.JAVA_VERSION }}
- name: Tar GraalVM JDK
shell: bash
run: tar -czvhf graalvm.tgz -C $(dirname ${GRAALVM_HOME}) $(basename ${GRAALVM_HOME})
- name: Persist GraalVM JDK build
uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # actions/upload-artifact@v4 | v4.6.2
with:
name: graalvm
path: graalvm.tgz
- name: Setup python
uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # actions/setup-python@v5 | v5.6.0
with:
python-version: '${{ env.PYTHON_VERSION }}'
- name: Populate matrix
id: set-matrix
run: python3 ${{ env.LIBRARY_METADATA_PATH }}/build_native_image_layer.py ${{ env.LIBRARY_METADATA_PATH }}/
test-native-image-layer-build:
name: ${{ matrix.coordinates }}
runs-on: ubuntu-latest
env:
GRAALVM_HOME: ${{ github.workspace }}/graalvm
timeout-minutes: 30
needs:  build-graalvm-and-populate-matrix
strategy:
fail-fast: false
matrix:
coordinates: ${{ fromJson(needs. build-graalvm-and-populate-matrix.outputs.matrix).coordinates }}
steps:
- name: Checkout oracle/graal
uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
- name: Download GraalVM JDK build
uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4.2.1
with:
name: graalvm
path: .
- name: Extract GraalVM JDK build
run: tar -xzvf graalvm.tgz -C $(dirname ${GRAALVM_HOME})
- name: "Setup JAVA_HOME"
uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # actions/setup-java@v4 | v4.7.1
with:
distribution: 'oracle'
java-version: ${{ env.JAVA_VERSION }}
- name: Setup python
uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # actions/setup-python@v5 | v5.6.0
with:
python-version: '${{ env.PYTHON_VERSION }}'
- name: Build layer
run: |
python3 ${{ env.LIBRARY_METADATA_PATH }}/build_native_image_layer.py ${{ env.GRAALVM_HOME }}/bin/native-image "${{ matrix.coordinates }}"