name: "Tests of validate package"
on:
push:
branches: [ master ]
pull_request:
branches: [ master ]
jobs:
unittest:
name: 'Run tests of validate package'
runs-on: ubuntu-latest
steps:
- name: Checkout repository
uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # actions/checkout@v2 | releases,850,v2.7.0
- name: Set up Python
uses: actions/setup-python@e9aba2c848f5ebd159c070c61ea2c4e2b122355e # actions/setup-python@v2 | releases,v2.3.4
with:
python-version: '3.8'
- name: Install dependencies
run: python -m pip install -r scripts/requirements.txt
- name: Run Unittest
run: |
cd scripts
python -m unittest discover tests/ --verbose