name: Creates a GitHub Issue when a PR Rolled back via Commit to Master
on:
push:
branches:
- master
permissions: {}
jobs:
create-issue-on-pr-rollback:
runs-on: ubuntu-latest
permissions:
contents: read
issues: write
pull-requests: read
if: |
github.repository == 'tensorflow/tensorflow' &&
startsWith(github.event.head_commit.message, 'Rollback of PR #')
steps:
- name: Checkout repo
uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
- name: Create a new Github Issue
uses: actions/github-script@60a0d83039c74a4aee543508d2ffcb1c3799cdea # v7.0.1
with:
github-token: ${{secrets.GITHUB_TOKEN}}
script: |
const script = require('./.github/workflows/create_issue.js')
console.log(await script({github, context}))