name: Set nightly branch to master HEAD
permissions: {}
jobs:
master-to-nightly:
if: github.repository == 'tensorflow/tensorflow' # Don't do this in forks
runs-on: ubuntu-latest
permissions:
contents: write
steps:
- uses: zofrex/mirror-branch@0be56f4c8077a288a635a491b306ba0bb1c810e6 # v1.0.4
name: Set nightly branch to master HEAD
with:
target-branch: 'nightly'