name: Upload bundler test manifests to areweturboyet.com
on:
schedule:
- cron: '0 8 * * *'
workflow_dispatch: {}
push:
branches:
- canary
paths:
- 'test/*-manifest.json'
jobs:
upload_test_results:
name: Upload test results
runs-on: ubuntu-latest
steps:
- name: Setup node
uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # actions/setup-node@v4 | v4.4.0
with:
node-version: ${{ env.NODE_LTS_VERSION }}
check-latest: true
- name: Checkout
uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # actions/checkout@v4 | v4.2.2
- name: Setup corepack
run: |
npm i -g corepack@0.31
corepack enable
- name: Install dependencies
shell: bash
run: pnpm i
- name: 'Upload results to "Are We Turbo Yet" KV'
env:
TURBOYET_KV_REST_API_URL: ${{ secrets.TURBOYET_KV_REST_API_URL }}
TURBOYET_KV_REST_API_TOKEN: ${{ secrets.TURBOYET_KV_REST_API_TOKEN }}
TURBOYET_TOKEN: ${{ secrets.TURBOYET_TOKEN }}
uses: ./.github/actions/upload-turboyet-data