name: 'ci'
on:
push:
branches:
- main
pull_request:
branches:
- main
jobs:
unit-test:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # actions/checkout@v2 | releases,850,v2.7.0
- name: Install pnpm
uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # pnpm/action-setup@v2
- name: Set node version to 18
uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # actions/setup-node@v2 | releases,v2.5.2
with:
node-version: 18
cache: 'pnpm'
- run: pnpm install
- name: Run unit tests
run: pnpm run test:unit
ssr-sfc-test:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # actions/checkout@v2 | releases,850,v2.7.0
- name: Install pnpm
uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # pnpm/action-setup@v2
- name: Set node version to 18
uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # actions/setup-node@v2 | releases,v2.5.2
with:
node-version: 18
cache: 'pnpm'
- run: pnpm install
- name: Run SSR tests
run: pnpm run test:ssr
- name: Run compiler-sfc tests
run: pnpm run test:sfc
e2e-test:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # actions/checkout@v2 | releases,850,v2.7.0
- name: Install pnpm
uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # pnpm/action-setup@v2
- name: Set node version to 18
uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # actions/setup-node@v2 | releases,v2.5.2
with:
node-version: 18
cache: 'pnpm'
- run: pnpm install
- name: Run e2e tests
run: pnpm run test:e2e
- name: Run transition tests
run: pnpm run test:transition
type-test:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # actions/checkout@v2 | releases,850,v2.7.0
- name: Install pnpm
uses: pnpm/action-setup@eae0cfeb286e66ffb5155f1a79b90583a127a68b # pnpm/action-setup@v2
- name: Set node version to 18
uses: actions/setup-node@7c12f8017d5436eb855f1ed4399f037a36fbd9e8 # actions/setup-node@v2 | releases,v2.5.2
with:
node-version: 18
cache: 'pnpm'
- run: pnpm install
- name: Run srouce type check
run: pnpm run ts-check
- name: Run type declaration tests
run: pnpm run test:types