name: Check Links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 3" # Every Wednesday at 00:00 UTC
  pull_request:
    paths:
      - ".github/workflows/check-links.yml"

jobs:
  check:
    runs-on: ubuntu-22.04
    if: github.repository == 'awslabs/amazon-ecr-credential-helper'
    name: lychee
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: lycheeverse/lychee-action@1d97d84f0bc547f7b25f4c2170d87d810dc2fb2c # v2.4.0
        with:
          fail: true
          args: --exclude-path ecr-login/vendor --timeout 30 --no-progress './**/*.md'
          format: markdown
          jobSummary: true
