name: Review dependencies

on:
  pull_request:
    branches: ['main', 'release/**']
    paths:
      - 'ecr-login/go.*'

jobs:
  review:
    runs-on: ubuntu-latest

    permissions:
      # Write permissions needed to comment review results on PR.
      # Pwn request risk mitigated by using pull_request workflow trigger
      # and external contributor workflow runs require maintainer approval.
      pull-requests: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/dependency-review-action@da24556b548a50705dd671f47852072ea4c105d9 # v4
        with:
          config-file: './.github/dependency-review-config.yml'
          comment-summary-in-pr: always
