name: NPM Tag
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
      tag:
        required: true
        default: "latest"
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      ############# TAG RELEASE ##############
      - name: Tag release
        run: npm dist-tag add axios@${{ github.event.inputs.version }} ${{ github.event.inputs.tag }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
