name: npm_publish

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version'
        type: string
  release:
    types: [published]

permissions:
  id-token: write

jobs:
  build:
    name: npm publish
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Configure git
        run: |
          git config --global core.symlinks true
          git config --global fetch.parallel 32

      - name: Clone repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          submodules: recursive

      - name: Install Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2
        with:
          deno-version: v2.x
      - name: Install Node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: ./tools/release/npm/build.ts ${{ github.event.inputs.version }} --publish
