name: free-programming-books-lint

on: [pull_request]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - name: Use Node.js
      uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
      with:
        node-version: '16.x'
    - run: npm install -g free-programming-books-lint

    - name: Pull Request
      run: |
        fpb-lint books casts courses more &> output.log

    - name: Clean output and create artifacts
      if: always()
      run: |
          mkdir -p ./pr
          echo ${{ github.event.pull_request.html_url }} > ./pr/PRurl
          cat output.log | sed -E 's:/home/runner/work/free-programming-books/|⚠.+::' | uniq > ./pr/error.log

    - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
      if: always()
      with:
        name: pr
        path: pr/
