name: Issue Needs Attention
# This workflow is triggered on issue comments.
on:
  issue_comment:
    types: created

jobs:
  applyNeedsAttentionLabel:
    name: Apply Needs Attention Label
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      - name: Apply Needs Attention Label
        uses: hramos/needs-attention@4d47f33c9b77fc9bf45670510c7847c382231317 # v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          response-required-label: 'waiting-for-response'
          needs-attention-label: 'needs-triage'
