name: Lint & Generate HTML from Markdown
on:
  push:
    branches:
      - master
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: .operations

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04
    env:
      NODE_ENV: test

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3

      - name: Setup Node.js environment
        uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version: "18"

      - run: npm install
      - run: npm run lint
