name: Rust

on:
  push:
    branches: ["main"]
    paths: ["codes/rust/**/*.rs", "codes/rust/Cargo.toml"]
  pull_request:
    branches: ["main"]
    paths: ["codes/rust/**/*.rs", "codes/rust/Cargo.toml"]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: brndnmtthws/rust-action-rustup@913349b802fe843511093e8c2014c94d8168c6b6 # v1
        with:
            toolchain: nightly
      
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      
      - name: Build
        run: cargo build --manifest-path=codes/rust/Cargo.toml && cargo build --manifest-path=codes/rust/Cargo.toml --release
