name: TypeScript

on:
  push:
    branches: ['main']
    paths: ['codes/typescript/**/*.ts']
  pull_request:
    branches: ['main']
    paths: ['codes/typescript/**/*.ts']
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20.x
      - name: Install dependencies
        run: cd codes/typescript && npm install
      - name: Check TypeScript code
        run: cd codes/typescript && npm run check
