---
name: Lint new or modified files using Super Linter

on:
  pull_request:
    branches: [main]

jobs:
  lint-new-modified-files:
    name: Lint new or modified files
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Git repository with history
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0

      - name: Set environment variables
        run: cat .github/super-linter.env >> "$GITHUB_ENV"

      - name: Run Super Linter
        uses: github/super-linter/slim@b807e99ddd37e444d189cfd2c2ca1274d8ae8ef1 # v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
