name: 'Upload a Build Artifact'
outbound-endpoints:
  - fqdn: pipelines.actions.githubusercontent.com
    port: 443
    reason: to upload artifact
harden-runner-link: https://app.stepsecurity.io/github/step-security/agent/actions/runs/1523253110